version: "2"
services:
    team-preview-analyst:
        build: .
        volumes:
            - ./:/src
            - /etc/localtime:/etc/localtime
        ports:
            - 8080
        environment:
            VIRTUAL_HOST: api.poyo.club
            LETSENCRYPT_HOST: api.poyo.club
            LETSENCRYPT_EMAIL: odan3240@gmail.com
            LETSENCRYPT_TEST: "false"
        entrypoint:
            - src/server.py
        network_mode: "bridge"

    staging:
        build: .
        volumes:
            - ./:/src
            - /etc/localtime:/etc/localtime
        environment:
            VIRTUAL_HOST: test.poyo.club
            LETSENCRYPT_HOST: test.poyo.club
            LETSENCRYPT_EMAIL: odan3240@gmail.com
            LETSENCRYPT_TEST: "false"
        entrypoint:
            - src/server.py
        network_mode: "bridge"
